### ISSUE TITLE
Duplicate Die Drop/Messages from Timer

### ISSUE THREAD

**Issue by Shuggaloaf** [SDoehren/tension-pool#23]
**Describe the bug**
When using the timer, either all, or every other, die drop gets duplicated. (1st noticed it was all, un/reinstalled and now it is every other die drop starting with the 2nd drop)

**To Reproduce**
Set a timer for something like 5 seconds
1st roll may or may not drop 1 die and 1 chat message
2nd roll will drop 2 die, 2 chat messages
*Note that even though the die drop and message duplicates, it still only adds 1 die to the pool.

**EDIT:** I just found that sometimes it will work all the way through filing the pool. Then when emptied it may start having the issue. Sometimes it starts from the very first pool/timer. Seems very intermittent so try a few times if you're not seeing it. 
The only "pattern" I'm seeing is that when it happens, it often happens with every other die drop. I'm wondering if this points to a possible rounding issue somewhere?

Also I tried with disabling all mods except those dependent and issue persists. 

**Screenshots**
<img src="https://user-images.githubusercontent.com/79543184/141358254-f9aea1b5-7cf3-4c5a-b7c0-15bbf06a5027.png" width="75%"/>

**Foundry (please complete the following information):**
 - Foundry Version 0.8.9
 - System DnD5e 1.5.3
 - Module Version 0053

**Desktop (please complete the following information):**
 - OS: [e.g. windows 10]

**Comment by SDoehren** [comment]
This was an issue that actually delayed released of this feature.  It is caused by simple calendar double reporting the time, I will need to relook into it as it was resolved.

The pattern used to be every 10th time report from simple calendar.

As a potential temporary fix I found manually adding 1 second to the time offsets the double report and stopped the issue in the passed.

**Comment by Shuggaloaf** [comment]
Hey SD thanks for the quick response. 

Very odd that it came back for me and at a higher rate than you even had in testing! 

>As a potential temporary fix I found manually adding 1 second to the time...

Can you explain this a little more? I'm guessing you mean more than just adding 1 second to the timer (like if I had it at 5 seconds, make it 6 seconds). Do you mean adding to the actual game time or something else?

*e: I've tested just adding 1 sec to the timer but (1) if under 10 seconds it doesn't help at all and (2) even over 10 seconds it still happens randomly.

**Comment by Shuggaloaf** [comment]
Hey @SDoehren sorry to bug you again on this, could you explain the "adding 1 second" method for me?

**Comment by SDoehren** [comment]
sorry for the delay.

Another method to try is start the clock, wait a second, pause it, then press play again. so

set up timer

start clock

wait a second for the clock to move forward

pause and then play again 


i previously found its to do with landing on the tenth second.  
i will be having a deeper look into this issue today.

**Comment by Shuggaloaf** [comment]
Thanks and no worries on the delay. :)
So that's just any dice drop that lands on a second divisible by 10? If so, that doesn't _seem_ to match what I am seeing. For example even if I set the timer to, say, 11 seconds it still happens every other drop. So I would get 
1 notification at 11 second
2 notifications at 22 seconds
1 notification at 33 second
2 notifications at 44 seconds
and so on. 

Just mentioning it in case it helps you narrow anything down. Good luck!

**Comment by SDoehren** [comment]
The issue is this is nothing to do with Tension Pool, it's 100% simple calendar.

Basically every so often Simple Calendar fires "updateWorldTime" twice in a second.  If this double occurs at the same time point as a drop is due, it will double drop.  

All that said, I might have found a solution.

**Comment by SDoehren** [comment]
V0055 has been released, this issue should be resolved.  Let me know if you have further issues.

**Comment by Shuggaloaf** [comment]
>The issue is this is nothing to do with Tension Pool, it's 100% simple calendar.

Oh yeah, I understood that. Sorry if it sounded like I was implying otherwise. :-)

Thanks for the fix, seems to be working great!
